---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bgd
  name: bgd
spec:
  nodeName: ip-10-0-141-60.ec2.internal
  replicas: 1
  selector:
    matchLabels:
      app: bgd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bgd
    spec:
      containers:
      - image: quay.io/jameswong/hello-world
        name: bgd
        env:
        - name: COLOR
          value: "blue"
        resources: {}
---
