apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgdk-app
  namespace: openshift-gitops
  annotations:
    argocd-image-updater.argoproj.io/image-list: hello=quay.io/jameswong/hello-world:~2.1.0,modelsvr=quay.io/jameswong/wisdom-model-server
    argocd-image-updater.argoproj.io/modelsvr.pull-secret: pullsecret:openshift-gitops/quay-pull-secret-james
    argocd-image-updater.argoproj.io/write-back-method: argocd
    # argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd-image-updater/git-creds
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/bgd/overlays/bgdk
    repoURL: https://github.com/jameswnl/openshift-gitops-examples
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true

